"""is contri hitory

Revision ID: 19634c1736bc
Revises: 2f5b388477a4
Create Date: 2026-04-05 23:34:47.489929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19634c1736bc'
down_revision = '2f5b388477a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_history', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.drop_column('is_history')

    # ### end Alembic commands ###
