"""rewading 5

Revision ID: 238b3d3173a8
Revises: 9db3a068f9ce
Create Date: 2026-04-06 22:48:59.684289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238b3d3173a8'
down_revision = '9db3a068f9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Reward_Category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_column('Reward_Category')

    # ### end Alembic commands ###
