"""rewading 3

Revision ID: 4662a2c2735e
Revises: b6c04148b26c
Create Date: 2026-04-06 14:46:08.807779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4662a2c2735e'
down_revision = 'b6c04148b26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Reward_Icone', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.drop_column('Reward_Icone')

    # ### end Alembic commands ###
