"""rewading 4

Revision ID: 9db3a068f9ce
Revises: 4662a2c2735e
Create Date: 2026-04-06 22:20:16.916701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db3a068f9ce'
down_revision = '4662a2c2735e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant_reward', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
