"""init migrations

Revision ID: ddea43c8e7df
Revises: 
Create Date: 2026-03-22 20:47:39.082572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddea43c8e7df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_contribution_category', 'category', ['Category_id'], ['Category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contribution_category', type_='foreignkey')
        batch_op.drop_column('Category_id')

    # ### end Alembic commands ###
