"""draft migrations

Revision ID: eff15ea99044
Revises: ddea43c8e7df
Create Date: 2026-03-22 21:33:38.436507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff15ea99044'
down_revision = 'ddea43c8e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.alter_column('item_type',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    # ### end Alembic commands ###
