"""rewading 1

Revision ID: fafcbde25a72
Revises: 19634c1736bc
Create Date: 2026-04-06 13:58:34.724980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fafcbde25a72'
down_revision = '19634c1736bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_name', sa.String(length=200), nullable=True))
        batch_op.drop_column('attribute_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reward', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribute_name', mysql.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('reward_name')

    # ### end Alembic commands ###
